export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REQUEST_BUILDINGS = 'REQUEST_BUILDINGS';
export const REQUEST_BUILDINGS_SUCCESS = 'REQUEST_BUILDINGS_SUCCESS';
export const REQUEST_BUILDINGS_FAILED = 'REQUEST_BUILDINGS_FAILED';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const SELECT_USER = 'SELECT_USER';
export const SELECT_USER_SUCCESS = 'SELECT_USER_SUCCESS';
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const CLEAR_PHOTOS = 'CLEAR_PHOTOS';
export const CLEAR_USERS = 'CLEAR_USERS';
